### PR TITLE
Fixed call to ottoman.validate

### PR DESCRIPTION
**Pull request by erik-etops**
Added tests for the validate call and exposed the callback as a necessary argument. The callback argument is needed by the schema. 
Note that this will necessitate a change to this documentation:
http://ottomanjs.com/Ottoman.html#validate

It might also be desirable to verify the model structure and types in the _validate function in schema.js.

### CODE REVIEW

**Comment by brett19** [comment]
Would you be able to squash this into a single commit?

**Comment by erik-etops** [comment]
Sure...uhh, I've never done that, stand by

**Comment by erik-etops** [comment]
I was surprised by that merge commit- is that my screw up?

**Comment by brett19** [comment]
Hey @erik-etops,
It does appear that this has gotten a bit crazy.  You should be able to google for 'git squash' for more information on how to squash all these commits to a single commit.  If you continue to have trouble getting it to work, let me know and I can make a new PR for this with it squashed.
Cheers, Brett

**Pull request closed without merging**
