### PR TITLE
namespace problem

### PR DESCRIPTION
**Pull request by ckaeslin**
This first commit just adds three unit tests to show the namespace problem.
So first commit is intended to fail.

Second commit provides a fix. Namespace has to be removed when in the toJSON method and if it is a mixed type to get the correct type.

Third commit adds the option the pass ottoman models from other ottoman instances with different namespaces, such that they can reference to each other.

### CODE REVIEW

**Comment by brett19** [comment]
Hey @ckaeslin,

Would you consider this 'complete' at this point?

Cheers, Brett

**Comment by ckaeslin** [comment]
for us this works so far, it will soon go into production

**Comment by brett19** [comment]
Hey @ckaeslin,
Any chance you could clean this PR up to a single commit so we can merge it?
Cheers, Brett

**Comment by brett19** [comment]
Hey @ckaeslin , if you are still actively working with Ottoman.js, please resubmit this commit rebased to the latest master and we will get it merged as soon as possible! Cheers, Brett

**Pull request closed without merging**
