### PR TITLE
toJSON implementation following Mongoose DBRef pattern, and unit tests

### PR DESCRIPTION
**Pull request by moxious**
See this issue for a full discussion: https://github.com/couchbaselabs/node-ottoman/issues/110

### CODE REVIEW

**Comment by brett19** [comment]
Hey @moxious ,
What is the difference between the DBRef implementation you've done here, and the reference format we already use within Ottoman?
Cheers, Brett

**Comment by moxious** [comment]
DBRef format looks like this:

```
{ 
  "$ref" : "MyModel", 
  "$id" : "someuuid", 
}
```

Internal ottoman representation looks like this:

```
{
   "$ref": "some-uuid",
   "_type": "MyModel"
}
```

So they're quite similar.  In previous discussion with you though, you had indicated that it's undesirable to expose these ottoman internals.   There's also the `_type` issue discussed a lot lately, which makes exposing `_type` definitely an unsafe bet.

Note that without this change, the ottoman internal format doesn't get exposed properly at all because it's an instance of a function and not an actual JSON object in memory.

See issue #110 linked for more details, and code examples of why this approach.

**Comment by brett19** [comment]
This looks good other than that I believe it will break backwards compatibility.  I'm going to have to think about the consequences of that before we merge.

**Comment by moxious** [comment]
I don't think this will break backwards compatibility -- or at least anyone in the past who depend ended on the toJSON function was making a mistake.  There were no unit tests for this function before, and in its previous implementation -- as I pointed out it returned a complex object with functions, not JSON.

Since toJSON before just returned the object, if people wrote code to this then they were already coupling to all sorts of internals that they shouldn't have, e.g. the `$` on the model would have been defined, since it was only returning `this`.  Variables like that are not part of any reasonable JSON serialization of a model.

By all means think about it and discuss, but even if this implementation isn't right, still something substantiatively different than what's there now is needed.

**Pull request merged**
