### PR TITLE
alternative to _type (leading underscore problem with sync gateway)

### PR DESCRIPTION
**Pull request by ckaeslin**
_type can be changed by setting env variable OTTOMAN_TYPE

I had the same issue as here: https://github.com/couchbaselabs/node-ottoman/issues/79
Therefore I made the "_type" configurable via environament variable.
If env variable is not set it uses the standard _type

### CODE REVIEW

**Comment by brett19** [comment]
Just to start a discussion here.  I think that making `_type` configurable is probably a good idea.  Perhaps it should be a configuration parameter of the top-level Ottoman object itself?  Note that ottoman supports 'low level' configuration like this through its object already, most people simply use the default Ottoman instance though.

**Comment by ckaeslin** [comment]
Did you mean with options? like I did in the latest commit or different?

**Comment by bhushano7** [comment]
When it'll be ready to use ?

**Comment by brett19** [comment]
This change will break the API compatibility for the CbStoreAdapter change.  Perhaps it would be better if we allowed the user to create the CbStoreAdapter object first, and then adjust a `typeField` property of that object, this will give us compatibility with old code.

**Pull request closed without merging**
