### PR TITLE
Dependency upgraded to address vulnerability

### PR DESCRIPTION
**Pull request by eduardobs79**
Upgraded jsonpath dependency to address vulnerability. Unit tests are OK.

### CODE REVIEW

**Comment by eduardobs79** [comment]
Can we get this merged? 👍

**Comment by reicruz** [comment]
@brett19 for context, this is to address a known minor NSP vulnerability found in a nested dependency

```
$ nsp check
(+) 1 vulnerability found
┌────────────┬────────────────────────────────────────────────────────────────────┐
│            │ Sandbox Breakout / Arbitrary Code Execution                        │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Name       │ static-eval                                                        │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ CVSS       │ 6.2 (Medium)                                                       │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Installed  │ 0.2.3                                                              │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Vulnerable │ <=1.1.1                                                            │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Patched    │ >=2.0.0                                                            │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Path       │ scm@1.15.5 > ottoman@1.0.5 > jsonpath@0.2.12 > static-eval@0.2.3   │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ More Info  │ https://nodesecurity.io/advisories/548                             │
└────────────┴────────────────────────────────────────────────────────────────────┘
```

**Comment by binaryword** [comment]
@brett19 Any news on this? Any module including ottoman will fail an NSP check due to this.

**Comment by sapkalrohan** [comment]
@brett19 have you abandoned ottomon? do we use it or move on?

**Comment by brett19** [comment]
Hey @sapkalrohan,

We've definitely not abandoned our plans with Ottoman.js, it's unfortunately been reprioritized for the moment.  We are expecting to have an opportunity to make improvements to Ottoman in the next few months.  We have Ottoman v2 mostly completed at this point and are going to be working through the remaining items for its release as soon as possible!

Cheers, Brett

**Pull request closed without merging**
