### PR TITLE
Switch from JSHint to ESlint

### PR DESCRIPTION
**Pull request by corbinu**
ESlint is a newer pluggable linter that does both the job of JSHint and JSCS (the JSCS team has actually joined the ESLint team) 

This PR is both a translation of the existing JSHint rules and a set of fixes based on issues found. It is structured so that if there is a rule you want changed it should be easy for me to rollback the commit and update the .eslintrc

Let me know if you have any questions or want any rule changes

### CODE REVIEW

**Comment by moxious** [comment]
I think it would be great to go to eslint instead of jshint, but what are all of those other changes on `lib/cbstoreadapter.js` about to the index logic?

**Comment by corbinu** [comment]
@moxious after converting the rules over eslint found a bunch of issues that jshint did not. I simply made the changes to make the rules pass.

**Comment by moxious** [comment]
Ah, I see - the way the diff presented it threw me a bit.  Well I'm not the maintainer, but I'd like to see this merged too.

**Comment by brett19** [comment]
This has been merged via rebase.

**Pull request closed without merging**
