### PR TITLE
Fixes Issue #610

### PR DESCRIPTION
**Pull request by zachlankton**
This pull request fixes issue #610 as well as passes all legacy and non legacy tests (without the `OTTOMAN_LEGACY_TEST=1` set).  

Intermittently there would be `LCB_ERR_KEYSPACE_NOT_FOUND` when creating new collections and indexes.  This would happen because sometimes the `ensureCollections` would return before the collections were actually ready.  Additionally sometimes there would be Query `Planning Failures` when running on freshly created models because the `ensureIndexes` would not return the `indexOnlinePromise` unless `indexReadyHooks` were defined.

The changes in this pull request refactor some logic in the `ensureCollections` and `ensureIndexes` functions.  It now guarantees that the collections and the indexes will be ready as described in the documentation.

### CODE REVIEW

**Comment by httpJunkie** [comment]
I've ran into some failed tests on both test and test:legacy so for this reason I am going to try and get one of our maintainers (Lino) to take a look at the PR and approve. But thank you for the PR, we are working on it.

**Comment by zachlankton** [comment]
Sounds good. Let me know if I can help!

**Review by httpJunkie — COMMENTED** [review]
We will be reviewing this PR this week. We may make changes to or replace this PR with something else that works the same. Either way, we will resolve this issue.

**Comment by zachlankton** [comment]
Quick update: I have been using the code in this pull request for about a month now and have not found any new issues! 😊

**Comment by ejscribner** [comment]
Thanks for the update @zachlankton!! I'll see what we can do about getting this into the next release. I appreciate the contribution!

**Comment by ejscribner** [comment]
@zachlankton We've updated the testing workflow to include PRs from branches in forks. Could you amend your last commit (just change a single character or something) to trigger the tests?

**Comment by zachlankton** [comment]
Looks like the tests are passing, but code coverage is failing for files and lines of code that this PR did not touch.  Looks like the same thing is happening in PR #614

**Comment by zachlankton** [comment]
Actually, just noticed codecov is comparing this pull request to an old commit from August — 1fb8ced

**Comment by ejscribner** [comment]
I believe this is ok for now, I'll touch base with the team tomorrow. Thanks so much @zachlankton!

**Review by ejscribner — APPROVED** [review]

**Comment by ejscribner** [comment]
Hey @zachlankton just a quick update on this: we're planning on including it in our next release (sometime next week I believe)! Thanks again for being a part of our growing community. Cheers!

**Pull request merged**
