### PR TITLE
Ottoman class has addValidators() function to register custom validat…

### PR DESCRIPTION
**Pull request by tcheever**
…ors.  They can be referenced by name (ie: 'myValidator') or by the function itself (ie: ottoman.validators.myValidator).

Enhancement issue #139

### CODE REVIEW

**Comment by brett19** [comment]
Hey @tcheever,

Perhaps it would be more convenient if we implemented the validator registration API more similarily to the existing 'registration APIs' that we have?  Perhaps providing a `ottoman.validator('name', function...)`?

Cheers, Brett

**Comment by tcheever** [comment]
Ok sure.  I've just loved libraries that let you supply an object with multiple "things" in one call, but it can be changed to your suggestion.

**Comment by brett19** [comment]
Maybe these are not mutually exclusive concepts and we can somehow allow both kinds?

**Comment by tcheever** [comment]
The function could accept an object in the first arg, but if its a string, then look for a function in a 2nd arg.  Then it supports both approaches.

**Comment by brett19** [comment]
Due to the age of this PR, I am going to close it, but will leave the related issue #139 open as it will be resolved with the release of Ottoman v2.

**Pull request closed without merging**
