### PR TITLE
Issue 86

### PR DESCRIPTION
**Pull request by moxious**
Fix for this issue:  https://github.com/couchbaselabs/node-ottoman/issues/86

Discussion on the ticket describes motivation why.

Note that the function ottoman uses for building GSI indexes is getting a bit complex, and with chains of callbacks that are necessary, it tends to get a bit more difficult to follow over time.  I could rewrite this function to use promises which would make the logic flow a lot easier to follow and maintain, but would require that I pull in bluebird as an external dependency for various API options it offers that default promises do not.   If that's desired, we can put in a separate issue to pull in bluebird and do a minor refactor there.  On this ticket I've opted not to go that route to keep this change minimal and isolated.

### CODE REVIEW

**Comment by moxious** [comment]
Build succeeds but fails on travis; I can't fix the travis build.  "Couchbase" is listed as an optional dependency but apparently isn't installed by travis, and it's a dependency for a test I wrote.

I think it would probably make sense to promote couchbase to a first-class dependency of ottoman.  Can you ever imagine a scenario running one without the other?

**Comment by brett19** [comment]
Rather than globally providing a H.liveTest, it is likely best if incase you check which adapter is currently activated.  You can do this with something like..
```javascript
if (ottoman.store instanceof ottoman.CbStoreAdapter) {
```

**Comment by moxious** [comment]
Rebased on top of the other whitespace PR -- and your comment above was fixed to remove the global H.liveTest in favor of instanceOf checking.

**Comment by brett19** [comment]
I made a minor modification of moving the `require('couchbase')` inside the if CbStoreAdapter check, since the couchbase dependancy is optional and might not have been installed.

Merged.

**Pull request closed without merging**
