### PR TITLE
Debug Support

### PR DESCRIPTION
**Pull request by bentonam**
Previously for debugging you had to set `ottoman.store.debug = true;` and there were conditions in the code i.e. `if (this.debug) { ... }`, all of those conditions have been removed and now debugging can be enabled/disabled through environment variables by using the [debug](https://www.npmjs.com/package/debug) module.  This will allow developers to view debugging information at any point in time, in any environment without needing to deploy a code change.

To see all of the available debug information:

```bash
export DEBUG='ottoman*'
```

To see all of the debug information except for MockStoreAdapter, Schema and Path

```bash
export DEBUG='ottoman*,-*MockStoreAdapter,-*Schema,-*Path'
```

To see just specific debug information related to CBStoreAdapter

```bash
export DEBUG='ottoman:CbStoreAdapter'
```

Example Output:

### CODE REVIEW

**Comment by brett19** [comment]
This is _awesome_.  Let me think about the versioning side-effects of this, but I definitely want to get this in to a release!

**Comment by bentonam** [comment]
@brett19 thanks! I wanted to add it to the Node SDK as well when I get a chance.  I wasn't sure if debug should be attached globally per file or attached specifically to each instance, but that can always be changed later. 

Two question: 
- Any thoughts on getting Node v0.10 and v0.12 to pass the build? 
- I had added Node 6, 7, 8, and 9 to Travis do you want those as the base or just the latest minor release for each i.e. 6.12, 7.10, 8.9, and 9.5?

**Comment by brett19** [comment]
Hey @bentonam ,

I'll have to take a look at v0.10 and v0.12 build passing.  I actually intended to refactor Ottoman.js to use some newer Node.js features which may end up causing us to deprecate those versions anyways though.  W.r.t. 6, 7, 8, 9: we typically we try to test against the latest minors of each major, though in practice, I don't think it would make a difference.

Cheers, Brett

**Comment by bentonam** [comment]
@brett19 have you considered using babel?  That way you could write new or even future compliant code and it will handle transpiling to the target system at install time? Just a thought, I've been doing that for quite awhile now to leverage features like async/await/destructing/etc. 

I'll update the `.travis.yml` to use the latest minor versions

**Comment by brett19** [comment]
@bentonam Babel was definitely on my radar, I just am a bit hesitant as the clone/build and npm install steps are not entirely trivial to set up nicely.  Either you are responsible for pre-babelling the code thats in the repo, or there is a required pre-install step which performs the transpilation at clone time.  Neither of these options felt very nice to me, but I think I've been coming around.

**Pull request closed without merging**
